name: AutoDeploy

# Controls when the workflow will run
on:
  schedule:
    # Trigger job every hour At minute 0
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Trigger Vercel Deploy Hook API
      - name: Trigger Vercel Deploy
        run: curl ${{secrets.DEPLOY_HOOK_API}}
